-- 연습 문제

--도서번호가 1인 도서의 이름
SELECT BOOKNAME
FROM BOOK
WHERE BOOKID = 1;

--가격이 20,000원 이상인 도서의 이름
SELECT BOOKNAME
FROM BOOK
WHERE PRICE >= 20000;

-- 박지성의 총 구매액
-- SubQuery
SELECT SUM(SALEPRICE) AS TOTALPRICE
FROM ORDERS
where CUSTID = (SELECT CUSTID
                FROM CUSTOMER
                WHERE NAME = '박지성');

SELECT SUM(O.SALEPRICE) AS TOTALPRICE
FROM ORDERS O
         INNER JOIN CUSTOMER C ON O.CUSTID = C.CUSTID
WHERE C.NAME = '박지성';

SELECT SUM(SALEPRICE)
FROM ORDERS
WHERE CUSTID = 1;

--박지성이 구매한 도서의 수
SELECT COUNT(ORDERID) AS COUNTBOOK
FROM ORDERS O
         INNER JOIN CUSTOMER C ON O.CUSTID = C.CUSTID
WHERE C.NAME = '박지성';

SELECT COUNT(SALEPRICE)
FROM ORDERS
WHERE CUSTID = 1;


--박지성이 구매한 도서의 출판사 수
SELECT COUNT(PUBLISHER) AS COUNTPUBLISHER
FROM BOOK B
         INNER JOIN ORDERS O ON B.BOOKID = O.BOOKID
WHERE O.CUSTID = (SELECT CUSTID
                  FROM CUSTOMER
                  WHERE NAME = '박지성');


SELECT COUNT(PUBLISHER)
FROM BOOK,
     ORDERS
WHERE BOOK.BOOKID = ORDERS.BOOKID
  AND ORDERS.CUSTID = 1;

--박지성이 구매한 도서의 이름, 가격, 정가와 판매가격의 차이
SELECT B.BOOKNAME, B.PRICE, B.PRICE - O.SALEPRICE AS DIFF
FROM BOOK B,
     CUSTOMER C,
     ORDERS O
WHERE B.BOOKID = O.BOOKID
  AND O.CUSTID = C.CUSTID
  AND C.NAME = '박지성';


--박지성이 구매하지 않은 도서의 이름
-- DISTINCT : 중복 데이터 제거
SELECT DISTINCT B.BOOKNAME
FROM BOOK B,
     ORDERS O,
     CUSTOMER C
WHERE B.BOOKID = O.BOOKID
  AND O.CUSTID = C.CUSTID
  AND C.NAME != '박지성';